[4기][3주차] Wordle 과제 제출 - 밈
woowahan-pjs/java-wordle pull request #27
Opened 2023-04-04 10:34 UTC by mrlee7

2023-04-09 12:59 UTC, akayj820 requested changes
밈님 안녕하세요! 이번 3차 과제 리뷰어를 맡게 된 와제라고 합니다. 저도 아직 많이 부족하지만 열심히 리뷰 작성해봤습니다:) 피드백 반영하시면서 의견이 조금 다르시거나 더 얘기 나누고 싶은 내용 있으시면 코멘트나 카톡으로 언제든 말씀 부탁드립니다!!! 감사합니다🙇🏻‍

2023-04-09 12:59 UTC, akayj820 commented on src/test/java/wordle/domain/LetterTest.java
> +class LetterTest {
다른 테스트 케이스처럼 @DisplayName 이나 메서드명을 통해 어떤 부분에 대한 테스트인지 명시해주시면 다음에 보실 때 더 좋을 것 같습니다:)

2023-04-09 12:59 UTC, akayj820 commented on src/main/java/wordle/domain/Word.java
> +    public String castWordsToString() {
이 메서드는 테스트 코드에서만 사용되고 있는 것 같은데 별도의 용도가 없다면 삭제해주셔도 괜찮을 것 같습니다🧐

2023-04-09 12:59 UTC, akayj820 commented on src/main/java/wordle/view/GameView.java
> +public class GameView {
GameView 내 메서드들은 별도로 인스턴스로 생성해서 호출하지 않더라도 static 메서드로 공유해서 사용할 수 있는 기능들인 것 같은데 static 메서드로 변경해보시는 건 어떨까요?

2023-04-09 12:59 UTC, akayj820 commented on src/main/java/wordle/view/GameView.java
> +        System.out.println();
줄바꿈 출력 시 참고해보시면 좋을 것 같아서 링크 하나 공유드립니다:)

https://donggov.tistory.com/53

2023-04-09 12:59 UTC, akayj820 commented on src/main/java/wordle/domain/Letter.java
> +    public Result compare(Letter target) {
정답에 대한 확인은 이미 Word 도메인에서 확인하고 있고, 여기 compare 메서드는 실제로 사용되고 있지는 않은 것 같은데 확인 한 번 부탁드립니다 😀

2023-04-11 10:51 UTC, mrlee7 commented on src/test/java/wordle/domain/LetterTest.java
> +class LetterTest {
엇 너무 좋습니다 👍 👍 
디테일한 점들을 추가적으로 챙기는 리뷰 반영 기간이 될 수 있도록 하겠습니다 :bow:

2023-04-11 10:54 UTC, mrlee7 commented
> 밈님 안녕하세요! 이번 3차 과제 리뷰어를 맡게 된 와제라고 합니다. 저도 아직 많이 부족하지만 열심히 리뷰 작성해봤습니다:) 피드백 반영하시면서 의견이 조금 다르시거나 더 얘기 나누고 싶은 내용 있으시면 코멘트나 카톡으로 언제든 말씀 부탁드립니다!!! 감사합니다🙇🏻‍

상세한 리뷰 남겨주셔서 너무너무 감사합니다 와제님 ❤️   
페어프로그래밍을 진행하면서 놓친 부분이 많았네요.. 😢  
말씀해주신 부분들 고민해보고, 수정하면서 스레드 남겨놓도록 하겠습니다.  
다시한번, 너무너무 감사합니다 와제님 :bow:

2023-09-04 14:13 UTC, closed without merging